version: '3'

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-123}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /var/lib/postgresql/data
    volumes:
       - postgres_data:/var/lib/postgresql/data
       - ./cm2.dump:/tmp/cm2.dump
    ports:
      - "54322:5432"
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-ale88andr@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_data:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app
    restart: unless-stopped

  cryman:
    container_name: cryman_container
    build: .
    command: bash -c "alembic upgrade head && python src/main.py"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app
    restart: unless-stopped

networks:
  app:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
