"""Update organisation table: add foreign chief_id

Revision ID: 2b8aa03dcd33
Revises: 8af009d58bc1
Create Date: 2025-01-29 09:27:27.306560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8aa03dcd33'
down_revision: Union[str, None] = '8af009d58bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_organisation', sa.Column('chief_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee_organisation', 'employee', ['chief_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_organisation', type_='foreignkey')
    op.drop_column('employee_organisation', 'chief_id')
    # ### end Alembic commands ###
