"""Update user table add filed: is_blocked

Revision ID: 32811bd4bea3
Revises: 3e1d77e16924
Create Date: 2024-12-02 09:12:14.376206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32811bd4bea3'
down_revision: Union[str, None] = '3e1d77e16924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_blocked')
    # ### end Alembic commands ###
