"""Update employee table

Revision ID: 43a0b29e5615
Revises: fc70c41161e2
Create Date: 2025-03-04 13:01:26.504023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a0b29e5615'
down_revision: Union[str, None] = 'fc70c41161e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_department_id_fkey', 'employee', type_='foreignkey')
    op.drop_constraint('employee_location_id_fkey', 'employee', type_='foreignkey')
    op.drop_constraint('employee_organisation_id_fkey', 'employee', type_='foreignkey')
    op.drop_constraint('employee_position_id_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'employee_position', ['position_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'employee_organisation', ['organisation_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'employee_department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'employee_location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_position_id_fkey', 'employee', 'employee_position', ['position_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('employee_organisation_id_fkey', 'employee', 'employee_organisation', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('employee_location_id_fkey', 'employee', 'employee_location', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('employee_department_id_fkey', 'employee', 'employee_department', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
