"""Create cryptography_grade table

Revision ID: 45e90a2712f7
Revises: 28320fabc47b
Create Date: 2025-03-04 07:41:09.697664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e90a2712f7'
down_revision: Union[str, None] = '28320fabc47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    grade_table = op.create_table('cryptography_grade',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('value', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('value')
    )

    op.bulk_insert(grade_table, [
        {"id": 1, "value": "КС1", "description": "КС1 - угроза непосредственно для документации на компоненты СФ и на ЭП, парольную и ключевую информацию ЭП, защищаемые электронные документы, микросхемы с микрокодом BIOS, а также информацию, идущую по каналам связи. Это базовое ПО"},
        {"id": 2, "value": "КС2", "description": "КС2 - угроза атаки как при условии нахождения в контролируемой зоне, так и за её пределами. К базовому ПО добавлен аппаратно-программный модуль доверенной загрузки (АПМДЗ) со сертификатом"},
        {"id": 3, "value": "КС3", "description": "КС3 - возможность третьих лиц войти в СВТ и базирующейся на них сфере функционирования. Состоит из программы КС2 и ПО для создания и контроля замкнутой программной среды"},
        {"id": 4, "value": "КВ1", "description": "КВ1 - означает угрозу атак в работе сигналов, сопровождающих функционирование СФ и ЭП."},
        {"id": 5, "value": "КВ2", "description": "КВ2 - позволит несанкционированному вторжению получать доступ к исходным текстам прикладного программного обеспечения, работающего с функциями программного обеспечения СКЗИ."},
        {"id": 6, "value": "КА1", "description": "КА1 - довольно серьёзная угроза. Третьи лица получают возможность проникновения к любому аппаратному компоненту СКЗИ, а также СФ, класс устройства СКЗИ, коррелирует со степенью защищённости ПДн."},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cryptography_grade')
    # ### end Alembic commands ###
