"""Update employees table: add field indexes

Revision ID: 80901f23a236
Revises: 19e1c3878be9
Create Date: 2024-12-09 06:27:18.006684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80901f23a236'
down_revision: Union[str, None] = '19e1c3878be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employee_is_security_staff'), 'employee', ['is_security_staff'], unique=False)
    op.create_index(op.f('ix_employee_is_worked'), 'employee', ['is_worked'], unique=False)
    op.create_index(op.f('ix_employee_surname'), 'employee', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_surname'), table_name='employee')
    op.drop_index(op.f('ix_employee_is_worked'), table_name='employee')
    op.drop_index(op.f('ix_employee_is_security_staff'), table_name='employee')
    # ### end Alembic commands ###
