"""Remove ondelete CASCADE in cryptography tables

Revision ID: 884d33584996
Revises: 43a0b29e5615
Create Date: 2025-03-05 13:15:08.472914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884d33584996'
down_revision: Union[str, None] = '43a0b29e5615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cryptography_key_carrier_carrier_type_id_fkey', 'cryptography_key_carrier', type_='foreignkey')
    op.create_foreign_key(None, 'cryptography_key_carrier', 'cryptography_key_carrier_type', ['carrier_type_id'], ['id'])
    op.drop_constraint('cryptography_key_document_equipment_id_fkey', 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint('cryptography_key_document_owner_id_fkey', 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint('cryptography_key_document_cryptography_version_id_fkey', 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint('cryptography_key_document_remove_act_record_id_fkey', 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint('cryptography_key_document_install_act_record_id_fkey', 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint('cryptography_key_document_carrier_id_fkey', 'cryptography_key_document', type_='foreignkey')
    op.create_foreign_key(None, 'cryptography_key_document', 'cryptography_act_record', ['install_act_record_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_key_document', 'equipment', ['equipment_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_key_document', 'cryptography_version', ['cryptography_version_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_key_document', 'employee', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_key_document', 'cryptography_key_carrier', ['carrier_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_key_document', 'cryptography_act_record', ['remove_act_record_id'], ['id'])
    op.drop_constraint('cryptography_model_manufacturer_id_fkey', 'cryptography_model', type_='foreignkey')
    op.create_foreign_key(None, 'cryptography_model', 'cryptography_manufacturer', ['manufacturer_id'], ['id'])
    op.drop_constraint('cryptography_version_responsible_user_id_fkey', 'cryptography_version', type_='foreignkey')
    op.drop_constraint('cryptography_version_install_act_record_id_fkey', 'cryptography_version', type_='foreignkey')
    op.drop_constraint('cryptography_version_model_id_fkey', 'cryptography_version', type_='foreignkey')
    op.drop_constraint('cryptography_version_remove_act_record_id_fkey', 'cryptography_version', type_='foreignkey')
    op.drop_constraint('cryptography_version_grade_id_fkey', 'cryptography_version', type_='foreignkey')
    op.create_foreign_key(None, 'cryptography_version', 'employee', ['responsible_user_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_version', 'cryptography_grade', ['grade_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_version', 'cryptography_act_record', ['remove_act_record_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_version', 'cryptography_act_record', ['install_act_record_id'], ['id'])
    op.create_foreign_key(None, 'cryptography_version', 'cryptography_model', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cryptography_version', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_version', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_version', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_version', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_version', type_='foreignkey')
    op.create_foreign_key('cryptography_version_grade_id_fkey', 'cryptography_version', 'cryptography_grade', ['grade_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_version_remove_act_record_id_fkey', 'cryptography_version', 'cryptography_act_record', ['remove_act_record_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_version_model_id_fkey', 'cryptography_version', 'cryptography_model', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_version_install_act_record_id_fkey', 'cryptography_version', 'cryptography_act_record', ['install_act_record_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_version_responsible_user_id_fkey', 'cryptography_version', 'employee', ['responsible_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cryptography_model', type_='foreignkey')
    op.create_foreign_key('cryptography_model_manufacturer_id_fkey', 'cryptography_model', 'cryptography_manufacturer', ['manufacturer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_key_document', type_='foreignkey')
    op.drop_constraint(None, 'cryptography_key_document', type_='foreignkey')
    op.create_foreign_key('cryptography_key_document_carrier_id_fkey', 'cryptography_key_document', 'cryptography_key_carrier', ['carrier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_key_document_install_act_record_id_fkey', 'cryptography_key_document', 'cryptography_act_record', ['install_act_record_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_key_document_remove_act_record_id_fkey', 'cryptography_key_document', 'cryptography_act_record', ['remove_act_record_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_key_document_cryptography_version_id_fkey', 'cryptography_key_document', 'cryptography_version', ['cryptography_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_key_document_owner_id_fkey', 'cryptography_key_document', 'employee', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cryptography_key_document_equipment_id_fkey', 'cryptography_key_document', 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cryptography_key_carrier', type_='foreignkey')
    op.create_foreign_key('cryptography_key_carrier_carrier_type_id_fkey', 'cryptography_key_carrier', 'cryptography_key_carrier_type', ['carrier_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
