"""Update user table is_password_temporary, last_logit_at, last_login_from

Revision ID: c321fe95d341
Revises: dd989f2ad354
Create Date: 2024-11-29 07:32:19.175284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c321fe95d341'
down_revision: Union[str, None] = 'dd989f2ad354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_password_temporary', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_from', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_from')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'is_password_temporary')
    # ### end Alembic commands ###
