"""Update user table

Revision ID: dd989f2ad354
Revises: 56f600311b16
Create Date: 2024-11-28 11:03:21.717947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd989f2ad354'
down_revision: Union[str, None] = '56f600311b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'employee_id')
    # ### end Alembic commands ###
