"""Update cryptography_model table

Revision ID: ea6bf6d5f141
Revises: fac5ed88d27d
Create Date: 2025-03-06 07:06:30.053474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6bf6d5f141'
down_revision: Union[str, None] = 'fac5ed88d27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptography_model', sa.Column('product_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cryptography_model', 'cryptography_product_type', ['product_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cryptography_model', type_='foreignkey')
    op.drop_column('cryptography_model', 'product_type_id')
    # ### end Alembic commands ###
