"""Update cryptography_version table

Revision ID: f8e85ea21ff1
Revises: 45e90a2712f7
Create Date: 2025-03-04 08:40:23.370487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e85ea21ff1'
down_revision: Union[str, None] = '45e90a2712f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptography_version', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cryptography_version', 'cryptography_grade', ['grade_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cryptography_version', type_='foreignkey')
    op.drop_column('cryptography_version', 'grade_id')
    # ### end Alembic commands ###
