"""Add cryptography_product_type table

Revision ID: fac5ed88d27d
Revises: 884d33584996
Create Date: 2025-03-06 06:58:47.224838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac5ed88d27d'
down_revision: Union[str, None] = '884d33584996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    t = op.create_table('cryptography_product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.bulk_insert(t, [
        {"id": 1, "value": "Программный", "description": "Вид СКЗИ представляющий собой отдельную программу, которую необходимо скачать, установить и настроить на рабочем месте. Они совместимы с популярными ОС и аппаратными платформами. Поддерживают работу по ГОСТ и обладают сертификатами соответствия ФСБ России к СКЗИ."},
        {"id": 2, "value": "Программно-аппаратный", "description": "Вид СКЗИ, которые встроены в устройство (токен) вместе с другими необходимыми для работы средствами. Используя программно-аппаратные СКЗИ, пользователь решает главную проблему программного вида. Устройству достаточно иметь доступ к сети, а процесс шифрования и дешифровки производится внутри носителя. "},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cryptography_product_type')
    # ### end Alembic commands ###
