"""Update cryptography_version rm 'grade' table

Revision ID: fc70c41161e2
Revises: f8e85ea21ff1
Create Date: 2025-03-04 10:10:43.479956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc70c41161e2'
down_revision: Union[str, None] = 'f8e85ea21ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptography_version', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptography_version', sa.Column('grade', postgresql.ENUM('KC1', 'KC2', 'KC3', 'KB1', 'KB2', 'KA1', name='cryptographygrade'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
